#!/usr/bin/env node

const fetch = require('node-fetch')
const assert = require('assert').strict
const util = require('util')

const data = {
  "TopicArn": "arn:aws:sns:us-east-1:123456:fake-topic",
  "Message": "{\"content\":\"fake\"}",
  "MessageId": "abcd"
}

const index = 'sns-messages'
const currentDate = new Date()
const day = ('0' + currentDate.getDate()).slice(-2)
const month = ('0' + (currentDate.getMonth() + 1)).slice(-2)
const year = currentDate.getFullYear()
const dailyIndex = `${index}-${year}.${month}.${day}`

const exit_on_err = err => {
  console.log(err)
  console.log('✖ Test failed')
  process.exit(1)
}

fetch('http://127.0.0.1:3000/sns-receiver/sns-messages/', {
  method: 'post',
  body: JSON.stringify(data)
}).then(
  // Wait few seconds to be sure that data has been inserted
  setTimeout(
    () => {
      fetch(`http://elastic:9200/${dailyIndex}/_search`, {
        method: 'get'
      }).then(
        res => {
          fetch(`http://elastic:9200/${dailyIndex}`, {
            method: 'delete'
          }).then(
            () => {
              try {
                assert.equal(res.status, 200)
              } catch (err) {
                exit_on_err(err)
              }

              res.json().then(
                json => {
                  console.log(`Elasticsearch index data: ${util.inspect(json, {showHidden: false, depth: null})}`)
                  const es_res = json.hits.hits
                  try {
                    // ==== Main tests here ====
                    assert.equal(es_res.length, 1)
                    assert.deepEqual(
                      es_res[0]._source,
                      {
                        TopicArn: 'arn:aws:sns:us-east-1:123456:fake-topic',
                        Message: { content: 'fake' },
                        MessageId: 'abcd'
                      }
                    )
                    assert.equal(es_res[0]._id, 'abcd')
                    assert.ok(es_res[0]._index.match(/^sns-messages-[0-9]{4}\.[0-9]{2}\.[0-9]{2}$/))
                    // === End of main tests ====
                  } catch (err) {
                    exit_on_err(err)
                  }
                  console.log('✔ All good')
                },
                exit_on_err
              )
            },
            exit_on_err
          )
        },
        exit_on_err
      )
    },
    1500
  )
)
